### ISSUE TITLE
Encoding error with non-Latin text

### ISSUE THREAD

**Issue by iturki** [codebox/wordvis#1]
I tried to run it with Arabic text, and it did not work. It generates a svg file (a huge one) but I see this error when I open it in chrome:

```
This page contains the following errors:
error on line 6 at column 5: Encoding error
Below is a rendering of the page up to the first error.
```

**Comment by codebox** [comment]
Latest commit should fix this issue - please let me know if it works for your text

**Comment by iturki** [comment]
I just tested it and it works perfectly!
Thanks!
